<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Command\Consumer' shared service.

$this->services['AppBundle\Command\Consumer'] = $instance = new \AppBundle\Command\Consumer();

$instance->setName('videoimporter:consumer');

return $instance;
