<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Command\Producer' shared service.

$this->services['AppBundle\Command\Producer'] = $instance = new \AppBundle\Command\Producer();

$instance->setName('videoimporter:producer');

return $instance;
