<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.core.infrastructure.service.glorf_import.glorf_import_service' shared service.

return $this->services['videoconsumer.core.infrastructure.service.glorf_import.glorf_import_service'] = new \AppBundle\Core\Infrastructure\Service\GlorfImport\GlorfImportService(${($_ = isset($this->services['videoconsumer.shared_kernel.infrastructure.service.json_parser.json_parser_service']) ? $this->services['videoconsumer.shared_kernel.infrastructure.service.json_parser.json_parser_service'] : $this->services['videoconsumer.shared_kernel.infrastructure.service.json_parser.json_parser_service'] = new \AppBundle\SharedKernel\Infrastructure\Service\JsonParser\JsonParserService()) && false ?: '_'}, ${($_ = isset($this->services['videoconsumer.core.infrastructure.service.video_data_dto_collection_builder.video_data_dto_collection_builder_service']) ? $this->services['videoconsumer.core.infrastructure.service.video_data_dto_collection_builder.video_data_dto_collection_builder_service'] : $this->services['videoconsumer.core.infrastructure.service.video_data_dto_collection_builder.video_data_dto_collection_builder_service'] = new \AppBundle\Core\Infrastructure\Service\VideoDataDTOCollectionBuilder\VideoDataDTOCollectionBuilderService()) && false ?: '_'});
