<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.shared_kernel.infrastructure.service.yaml_parser.yaml_parser_service' shared service.

return $this->services['videoconsumer.shared_kernel.infrastructure.service.yaml_parser.yaml_parser_service'] = new \AppBundle\SharedKernel\Infrastructure\Service\YamlParser\YamlParserService();
