<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.shared_kernel.infrastructure.persistence.cassandra.cassandra_entity_repository' shared service.

return $this->services['videoconsumer.shared_kernel.infrastructure.persistence.cassandra.cassandra_entity_repository'] = new \AppBundle\SharedKernel\Infrastructure\Persistence\Cassandra\CassandraEntityRepository();
