<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.core.infrastructure.service.flub_import.flub_import_service' shared service.

return $this->services['videoconsumer.core.infrastructure.service.flub_import.flub_import_service'] = new \AppBundle\Core\Infrastructure\Service\FlubImport\FlubImportService(${($_ = isset($this->services['videoconsumer.shared_kernel.infrastructure.service.yaml_parser.yaml_parser_service']) ? $this->services['videoconsumer.shared_kernel.infrastructure.service.yaml_parser.yaml_parser_service'] : $this->services['videoconsumer.shared_kernel.infrastructure.service.yaml_parser.yaml_parser_service'] = new \AppBundle\SharedKernel\Infrastructure\Service\YamlParser\YamlParserService()) && false ?: '_'}, ${($_ = isset($this->services['videoconsumer.core.infrastructure.service.video_data_dto_collection_builder.video_data_dto_collection_builder_service']) ? $this->services['videoconsumer.core.infrastructure.service.video_data_dto_collection_builder.video_data_dto_collection_builder_service'] : $this->services['videoconsumer.core.infrastructure.service.video_data_dto_collection_builder.video_data_dto_collection_builder_service'] = new \AppBundle\Core\Infrastructure\Service\VideoDataDTOCollectionBuilder\VideoDataDTOCollectionBuilderService()) && false ?: '_'});
