<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.core.application.service.consume_from_queue.consume_from_queue_use_case' shared service.

return $this->services['videoconsumer.core.application.service.consume_from_queue.consume_from_queue_use_case'] = new \AppBundle\Core\Application\Services\ConsumeFromQueue\ConsumeFromQueueUseCase(${($_ = isset($this->services['videoconsumer.core.infrastructure.services.consume_and_persist.consume_and_persist_service']) ? $this->services['videoconsumer.core.infrastructure.services.consume_and_persist.consume_and_persist_service'] : $this->load(__DIR__.'/getVideoconsumer_Core_Infrastructure_Services_ConsumeAndPersist_ConsumeAndPersistServiceService.php')) && false ?: '_'});
