<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.core.infrastructure.service.video_data_dto_collection_builder.video_data_dto_collection_builder_service' shared service.

return $this->services['videoconsumer.core.infrastructure.service.video_data_dto_collection_builder.video_data_dto_collection_builder_service'] = new \AppBundle\Core\Infrastructure\Service\VideoDataDTOCollectionBuilder\VideoDataDTOCollectionBuilderService();
