<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.shared_kernel.infrastructure.persistence.doctrine.doctrine_entity_repository' shared service.

return $this->services['videoconsumer.shared_kernel.infrastructure.persistence.doctrine.doctrine_entity_repository'] = new \SharedKernel\Infrastructure\Persistence\Doctrine\DoctrineEntityRepository(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load(__DIR__.'/getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
