<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.core.infrastructure.service.build_video_aggregate.build_video_aggregate_service' shared service.

return $this->services['videoconsumer.core.infrastructure.service.build_video_aggregate.build_video_aggregate_service'] = new \AppBundle\Core\Infrastructure\Service\BuildVideoAggregate\BuildVideoAggregateService();
