<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.core.infrastructure.repository.doctrine_video_repository' shared service.

return $this->services['videoconsumer.core.infrastructure.repository.doctrine_video_repository'] = new \AppBundle\Core\Infrastructure\Repository\DoctrineVideoRepository();
