<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.core.application.service.import_videos_from_provider.import_videos_from_provider_use_case' shared service.

return $this->services['videoconsumer.core.application.service.import_videos_from_provider.import_videos_from_provider_use_case'] = new \AppBundle\Core\Application\Service\ImportVideosFromProvider\ImportVideosFromProviderUseCase(${($_ = isset($this->services['videoconsumer.core.domain.service.import_videos_from_provider.import_videos_from_provider_service']) ? $this->services['videoconsumer.core.domain.service.import_videos_from_provider.import_videos_from_provider_service'] : $this->load(__DIR__.'/getVideoconsumer_Core_Domain_Service_ImportVideosFromProvider_ImportVideosFromProviderServiceService.php')) && false ?: '_'});
