<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.infrastructure.service.datatransformer.message_datatransformer' shared service.

return $this->services['videoconsumer.infrastructure.service.datatransformer.message_datatransformer'] = new \AppBundle\Core\Infrastructure\DataTransformer\MessageDataTransformer();
