<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'videoconsumer.shared_kernel.infrastructure.queue_service.rabbit_mq_queue_adapter_service' shared service.

return $this->services['videoconsumer.shared_kernel.infrastructure.queue_service.rabbit_mq_queue_adapter_service'] = new \AppBundle\SharedKernel\Infrastructure\Queue\Service\RabbitMqQueueAdapterService();
