<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFtm57ld\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFtm57ld/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFtm57ld.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFtm57ld\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFtm57ld\appDevDebugProjectContainer();
