<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSls3yci\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSls3yci/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSls3yci.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSls3yci\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSls3yci\appDevDebugProjectContainer();
